# Generated by Django 2.1.2 on 2018-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfig',
            name='app_name',
            field=models.CharField(blank=True, help_text="The name of the app where the model you'd like to analyse is defined.", max_length=255),
        ),
    ]
